# Citybrain nginx Dockerfile
# Version 2.0
# Base images 基础镜像
FROM nginx:1.16.0-alpine
#MAINTAINER 维护者信息
LABEL caosx caosx@watone.com.cn
#ENV
ENV RUN_USER nginx
ENV RUN_GROUP nginx
#COPY
COPY ./resource/ /usr/share/nginx/html/
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/conf.d/default.conf /etc/nginx/conf.d/default.conf
#RUN
RUN chown -R nginx. /usr/share/nginx
RUN chmod +r /usr/share/nginx/html
#EXPOSE 映射端口
EXPOSE 7777
#CMD 运行以下命令
CMD ["nginx", "-g", "daemon off;"]
